﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using Refit;
using System.Threading.Tasks;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace FermentationController
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIFermentationControllerAPI : IFermentationControllerAPI
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIFermentationControllerAPI(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<string> Echo(string data)
        {
            var arguments = new object[] { data };
            return (Task<string>) methodImpls["Echo"](Client, arguments);
        }

        public virtual Task<string> GetAllProfiles()
        {
            var arguments = new object[] {  };
            return (Task<string>) methodImpls["GetAllProfiles"](Client, arguments);
        }

        public virtual Task<string> GetProfile(string id)
        {
            var arguments = new object[] { id };
            return (Task<string>) methodImpls["GetProfile"](Client, arguments);
        }

        public virtual Task Profile(string payload)
        {
            var arguments = new object[] { payload };
            return (Task) methodImpls["Profile"](Client, arguments);
        }

    }
}


